services:
  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    working_dir: /app/apps/auth-service
    command: npm run dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    volumes:
      - .:/app
      - /app/node_modules # Prevent local node_modules from overwriting inside container
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 # Ensure Redis binds to all interfaces for Docker connectivity
